language: php
php: 
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  # - hhvm # on Trusty only
  # - nightly
before_install:
  composer require php-coveralls/php-coveralls '^2.0'
install:
  - composer install --no-interaction
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_success:
  - ./vendor/bin/php-coveralls -v
